// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"
	"time"

	"github.com/alphagov/paas-aiven-broker/provider/aiven"
)

type FakeClient struct {
	CreateServiceStub        func(params *aiven.CreateServiceInput) (string, error)
	createServiceMutex       sync.RWMutex
	createServiceArgsForCall []struct {
		params *aiven.CreateServiceInput
	}
	createServiceReturns struct {
		result1 string
		result2 error
	}
	createServiceReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	GetServiceStatusStub        func(params *aiven.GetServiceInput) (aiven.ServiceStatus, time.Time, error)
	getServiceStatusMutex       sync.RWMutex
	getServiceStatusArgsForCall []struct {
		params *aiven.GetServiceInput
	}
	getServiceStatusReturns struct {
		result1 aiven.ServiceStatus
		result2 time.Time
		result3 error
	}
	getServiceStatusReturnsOnCall map[int]struct {
		result1 aiven.ServiceStatus
		result2 time.Time
		result3 error
	}
	GetServiceConnectionDetailsStub        func(params *aiven.GetServiceInput) (string, string, error)
	getServiceConnectionDetailsMutex       sync.RWMutex
	getServiceConnectionDetailsArgsForCall []struct {
		params *aiven.GetServiceInput
	}
	getServiceConnectionDetailsReturns struct {
		result1 string
		result2 string
		result3 error
	}
	getServiceConnectionDetailsReturnsOnCall map[int]struct {
		result1 string
		result2 string
		result3 error
	}
	DeleteServiceStub        func(params *aiven.DeleteServiceInput) (string, int, error)
	deleteServiceMutex       sync.RWMutex
	deleteServiceArgsForCall []struct {
		params *aiven.DeleteServiceInput
	}
	deleteServiceReturns struct {
		result1 string
		result2 int
		result3 error
	}
	deleteServiceReturnsOnCall map[int]struct {
		result1 string
		result2 int
		result3 error
	}
	CreateServiceUserStub        func(params *aiven.CreateServiceUserInput) (string, error)
	createServiceUserMutex       sync.RWMutex
	createServiceUserArgsForCall []struct {
		params *aiven.CreateServiceUserInput
	}
	createServiceUserReturns struct {
		result1 string
		result2 error
	}
	createServiceUserReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	DeleteServiceUserStub        func(params *aiven.DeleteServiceUserInput) (string, error)
	deleteServiceUserMutex       sync.RWMutex
	deleteServiceUserArgsForCall []struct {
		params *aiven.DeleteServiceUserInput
	}
	deleteServiceUserReturns struct {
		result1 string
		result2 error
	}
	deleteServiceUserReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	UpdateServiceStub        func(params *aiven.UpdateServiceInput) (string, error)
	updateServiceMutex       sync.RWMutex
	updateServiceArgsForCall []struct {
		params *aiven.UpdateServiceInput
	}
	updateServiceReturns struct {
		result1 string
		result2 error
	}
	updateServiceReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeClient) CreateService(params *aiven.CreateServiceInput) (string, error) {
	fake.createServiceMutex.Lock()
	ret, specificReturn := fake.createServiceReturnsOnCall[len(fake.createServiceArgsForCall)]
	fake.createServiceArgsForCall = append(fake.createServiceArgsForCall, struct {
		params *aiven.CreateServiceInput
	}{params})
	fake.recordInvocation("CreateService", []interface{}{params})
	fake.createServiceMutex.Unlock()
	if fake.CreateServiceStub != nil {
		return fake.CreateServiceStub(params)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.createServiceReturns.result1, fake.createServiceReturns.result2
}

func (fake *FakeClient) CreateServiceCallCount() int {
	fake.createServiceMutex.RLock()
	defer fake.createServiceMutex.RUnlock()
	return len(fake.createServiceArgsForCall)
}

func (fake *FakeClient) CreateServiceArgsForCall(i int) *aiven.CreateServiceInput {
	fake.createServiceMutex.RLock()
	defer fake.createServiceMutex.RUnlock()
	return fake.createServiceArgsForCall[i].params
}

func (fake *FakeClient) CreateServiceReturns(result1 string, result2 error) {
	fake.CreateServiceStub = nil
	fake.createServiceReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) CreateServiceReturnsOnCall(i int, result1 string, result2 error) {
	fake.CreateServiceStub = nil
	if fake.createServiceReturnsOnCall == nil {
		fake.createServiceReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.createServiceReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) GetServiceStatus(params *aiven.GetServiceInput) (aiven.ServiceStatus, time.Time, error) {
	fake.getServiceStatusMutex.Lock()
	ret, specificReturn := fake.getServiceStatusReturnsOnCall[len(fake.getServiceStatusArgsForCall)]
	fake.getServiceStatusArgsForCall = append(fake.getServiceStatusArgsForCall, struct {
		params *aiven.GetServiceInput
	}{params})
	fake.recordInvocation("GetServiceStatus", []interface{}{params})
	fake.getServiceStatusMutex.Unlock()
	if fake.GetServiceStatusStub != nil {
		return fake.GetServiceStatusStub(params)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fake.getServiceStatusReturns.result1, fake.getServiceStatusReturns.result2, fake.getServiceStatusReturns.result3
}

func (fake *FakeClient) GetServiceStatusCallCount() int {
	fake.getServiceStatusMutex.RLock()
	defer fake.getServiceStatusMutex.RUnlock()
	return len(fake.getServiceStatusArgsForCall)
}

func (fake *FakeClient) GetServiceStatusArgsForCall(i int) *aiven.GetServiceInput {
	fake.getServiceStatusMutex.RLock()
	defer fake.getServiceStatusMutex.RUnlock()
	return fake.getServiceStatusArgsForCall[i].params
}

func (fake *FakeClient) GetServiceStatusReturns(result1 aiven.ServiceStatus, result2 time.Time, result3 error) {
	fake.GetServiceStatusStub = nil
	fake.getServiceStatusReturns = struct {
		result1 aiven.ServiceStatus
		result2 time.Time
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeClient) GetServiceStatusReturnsOnCall(i int, result1 aiven.ServiceStatus, result2 time.Time, result3 error) {
	fake.GetServiceStatusStub = nil
	if fake.getServiceStatusReturnsOnCall == nil {
		fake.getServiceStatusReturnsOnCall = make(map[int]struct {
			result1 aiven.ServiceStatus
			result2 time.Time
			result3 error
		})
	}
	fake.getServiceStatusReturnsOnCall[i] = struct {
		result1 aiven.ServiceStatus
		result2 time.Time
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeClient) GetServiceConnectionDetails(params *aiven.GetServiceInput) (string, string, error) {
	fake.getServiceConnectionDetailsMutex.Lock()
	ret, specificReturn := fake.getServiceConnectionDetailsReturnsOnCall[len(fake.getServiceConnectionDetailsArgsForCall)]
	fake.getServiceConnectionDetailsArgsForCall = append(fake.getServiceConnectionDetailsArgsForCall, struct {
		params *aiven.GetServiceInput
	}{params})
	fake.recordInvocation("GetServiceConnectionDetails", []interface{}{params})
	fake.getServiceConnectionDetailsMutex.Unlock()
	if fake.GetServiceConnectionDetailsStub != nil {
		return fake.GetServiceConnectionDetailsStub(params)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fake.getServiceConnectionDetailsReturns.result1, fake.getServiceConnectionDetailsReturns.result2, fake.getServiceConnectionDetailsReturns.result3
}

func (fake *FakeClient) GetServiceConnectionDetailsCallCount() int {
	fake.getServiceConnectionDetailsMutex.RLock()
	defer fake.getServiceConnectionDetailsMutex.RUnlock()
	return len(fake.getServiceConnectionDetailsArgsForCall)
}

func (fake *FakeClient) GetServiceConnectionDetailsArgsForCall(i int) *aiven.GetServiceInput {
	fake.getServiceConnectionDetailsMutex.RLock()
	defer fake.getServiceConnectionDetailsMutex.RUnlock()
	return fake.getServiceConnectionDetailsArgsForCall[i].params
}

func (fake *FakeClient) GetServiceConnectionDetailsReturns(result1 string, result2 string, result3 error) {
	fake.GetServiceConnectionDetailsStub = nil
	fake.getServiceConnectionDetailsReturns = struct {
		result1 string
		result2 string
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeClient) GetServiceConnectionDetailsReturnsOnCall(i int, result1 string, result2 string, result3 error) {
	fake.GetServiceConnectionDetailsStub = nil
	if fake.getServiceConnectionDetailsReturnsOnCall == nil {
		fake.getServiceConnectionDetailsReturnsOnCall = make(map[int]struct {
			result1 string
			result2 string
			result3 error
		})
	}
	fake.getServiceConnectionDetailsReturnsOnCall[i] = struct {
		result1 string
		result2 string
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeClient) DeleteService(params *aiven.DeleteServiceInput) (string, int, error) {
	fake.deleteServiceMutex.Lock()
	ret, specificReturn := fake.deleteServiceReturnsOnCall[len(fake.deleteServiceArgsForCall)]
	fake.deleteServiceArgsForCall = append(fake.deleteServiceArgsForCall, struct {
		params *aiven.DeleteServiceInput
	}{params})
	fake.recordInvocation("DeleteService", []interface{}{params})
	fake.deleteServiceMutex.Unlock()
	if fake.DeleteServiceStub != nil {
		return fake.DeleteServiceStub(params)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fake.deleteServiceReturns.result1, fake.deleteServiceReturns.result2, fake.deleteServiceReturns.result3
}

func (fake *FakeClient) DeleteServiceCallCount() int {
	fake.deleteServiceMutex.RLock()
	defer fake.deleteServiceMutex.RUnlock()
	return len(fake.deleteServiceArgsForCall)
}

func (fake *FakeClient) DeleteServiceArgsForCall(i int) *aiven.DeleteServiceInput {
	fake.deleteServiceMutex.RLock()
	defer fake.deleteServiceMutex.RUnlock()
	return fake.deleteServiceArgsForCall[i].params
}

func (fake *FakeClient) DeleteServiceReturns(result1 string, result2 int, result3 error) {
	fake.DeleteServiceStub = nil
	fake.deleteServiceReturns = struct {
		result1 string
		result2 int
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeClient) DeleteServiceReturnsOnCall(i int, result1 string, result2 int, result3 error) {
	fake.DeleteServiceStub = nil
	if fake.deleteServiceReturnsOnCall == nil {
		fake.deleteServiceReturnsOnCall = make(map[int]struct {
			result1 string
			result2 int
			result3 error
		})
	}
	fake.deleteServiceReturnsOnCall[i] = struct {
		result1 string
		result2 int
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeClient) CreateServiceUser(params *aiven.CreateServiceUserInput) (string, error) {
	fake.createServiceUserMutex.Lock()
	ret, specificReturn := fake.createServiceUserReturnsOnCall[len(fake.createServiceUserArgsForCall)]
	fake.createServiceUserArgsForCall = append(fake.createServiceUserArgsForCall, struct {
		params *aiven.CreateServiceUserInput
	}{params})
	fake.recordInvocation("CreateServiceUser", []interface{}{params})
	fake.createServiceUserMutex.Unlock()
	if fake.CreateServiceUserStub != nil {
		return fake.CreateServiceUserStub(params)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.createServiceUserReturns.result1, fake.createServiceUserReturns.result2
}

func (fake *FakeClient) CreateServiceUserCallCount() int {
	fake.createServiceUserMutex.RLock()
	defer fake.createServiceUserMutex.RUnlock()
	return len(fake.createServiceUserArgsForCall)
}

func (fake *FakeClient) CreateServiceUserArgsForCall(i int) *aiven.CreateServiceUserInput {
	fake.createServiceUserMutex.RLock()
	defer fake.createServiceUserMutex.RUnlock()
	return fake.createServiceUserArgsForCall[i].params
}

func (fake *FakeClient) CreateServiceUserReturns(result1 string, result2 error) {
	fake.CreateServiceUserStub = nil
	fake.createServiceUserReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) CreateServiceUserReturnsOnCall(i int, result1 string, result2 error) {
	fake.CreateServiceUserStub = nil
	if fake.createServiceUserReturnsOnCall == nil {
		fake.createServiceUserReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.createServiceUserReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) DeleteServiceUser(params *aiven.DeleteServiceUserInput) (string, error) {
	fake.deleteServiceUserMutex.Lock()
	ret, specificReturn := fake.deleteServiceUserReturnsOnCall[len(fake.deleteServiceUserArgsForCall)]
	fake.deleteServiceUserArgsForCall = append(fake.deleteServiceUserArgsForCall, struct {
		params *aiven.DeleteServiceUserInput
	}{params})
	fake.recordInvocation("DeleteServiceUser", []interface{}{params})
	fake.deleteServiceUserMutex.Unlock()
	if fake.DeleteServiceUserStub != nil {
		return fake.DeleteServiceUserStub(params)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.deleteServiceUserReturns.result1, fake.deleteServiceUserReturns.result2
}

func (fake *FakeClient) DeleteServiceUserCallCount() int {
	fake.deleteServiceUserMutex.RLock()
	defer fake.deleteServiceUserMutex.RUnlock()
	return len(fake.deleteServiceUserArgsForCall)
}

func (fake *FakeClient) DeleteServiceUserArgsForCall(i int) *aiven.DeleteServiceUserInput {
	fake.deleteServiceUserMutex.RLock()
	defer fake.deleteServiceUserMutex.RUnlock()
	return fake.deleteServiceUserArgsForCall[i].params
}

func (fake *FakeClient) DeleteServiceUserReturns(result1 string, result2 error) {
	fake.DeleteServiceUserStub = nil
	fake.deleteServiceUserReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) DeleteServiceUserReturnsOnCall(i int, result1 string, result2 error) {
	fake.DeleteServiceUserStub = nil
	if fake.deleteServiceUserReturnsOnCall == nil {
		fake.deleteServiceUserReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.deleteServiceUserReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) UpdateService(params *aiven.UpdateServiceInput) (string, error) {
	fake.updateServiceMutex.Lock()
	ret, specificReturn := fake.updateServiceReturnsOnCall[len(fake.updateServiceArgsForCall)]
	fake.updateServiceArgsForCall = append(fake.updateServiceArgsForCall, struct {
		params *aiven.UpdateServiceInput
	}{params})
	fake.recordInvocation("UpdateService", []interface{}{params})
	fake.updateServiceMutex.Unlock()
	if fake.UpdateServiceStub != nil {
		return fake.UpdateServiceStub(params)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.updateServiceReturns.result1, fake.updateServiceReturns.result2
}

func (fake *FakeClient) UpdateServiceCallCount() int {
	fake.updateServiceMutex.RLock()
	defer fake.updateServiceMutex.RUnlock()
	return len(fake.updateServiceArgsForCall)
}

func (fake *FakeClient) UpdateServiceArgsForCall(i int) *aiven.UpdateServiceInput {
	fake.updateServiceMutex.RLock()
	defer fake.updateServiceMutex.RUnlock()
	return fake.updateServiceArgsForCall[i].params
}

func (fake *FakeClient) UpdateServiceReturns(result1 string, result2 error) {
	fake.UpdateServiceStub = nil
	fake.updateServiceReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) UpdateServiceReturnsOnCall(i int, result1 string, result2 error) {
	fake.UpdateServiceStub = nil
	if fake.updateServiceReturnsOnCall == nil {
		fake.updateServiceReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.updateServiceReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.createServiceMutex.RLock()
	defer fake.createServiceMutex.RUnlock()
	fake.getServiceStatusMutex.RLock()
	defer fake.getServiceStatusMutex.RUnlock()
	fake.getServiceConnectionDetailsMutex.RLock()
	defer fake.getServiceConnectionDetailsMutex.RUnlock()
	fake.deleteServiceMutex.RLock()
	defer fake.deleteServiceMutex.RUnlock()
	fake.createServiceUserMutex.RLock()
	defer fake.createServiceUserMutex.RUnlock()
	fake.deleteServiceUserMutex.RLock()
	defer fake.deleteServiceUserMutex.RUnlock()
	fake.updateServiceMutex.RLock()
	defer fake.updateServiceMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ aiven.Client = new(FakeClient)
