name: Go
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
env:
  GO_VERSION: "1.23"
jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: "Install Go ${{env.GO_VERSION}}"
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491
        with:
          go-version: "${{env.GO_VERSION}}"

      - name: Run tests
        run: |
          make unit
